services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Endroid\TileBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
